export const SYNTHETIC_DEMO_DATA = {
  products: [
    {
      id: "GC-CRISPR-KO",
      company: "GeneCopoeia",
      productName: "SureVector Lentiviral CRISPR Knockout Kit",
      catalogNumber: "HCP256001-LVSG03",
      rrid: "RRID:AB_3099001",
      productType: "CRISPR reagent",
      applicationArea: "Genome editing",
      synonyms: ["SureVector CRISPR KO Kit", "LVSG03 knockout kit", "GeneCopoeia CRISPR KO"],
      competitorEquivalents: ["Synthego CRISPR Kit", "Dharmacon Edit-R sgRNA", "Addgene lentiCRISPR"],
      internalOwner: "Genome Editing PM"
    },
    {
      id: "GC-ORF-CLONE",
      company: "GeneCopoeia",
      productName: "OmicsLink ORF Expression Clone",
      catalogNumber: "EX-HU12345-M02",
      rrid: "RRID:AB_3099002",
      productType: "ORF clone",
      applicationArea: "Gene expression",
      synonyms: ["OmicsLink ORF clone", "ORF expression construct", "EX-HU12345"],
      competitorEquivalents: ["OriGene TrueORF Clone", "GenScript ORF Clone"],
      internalOwner: "Expression Products PM"
    },
    {
      id: "GC-MIRNA-CLONE",
      company: "GeneCopoeia",
      productName: "miExpress Precursor miRNA Clone",
      catalogNumber: "HMIR0001-MR04",
      rrid: "RRID:AB_3099003",
      productType: "miRNA reagent",
      applicationArea: "RNA biology",
      synonyms: ["miExpress miRNA clone", "precursor miRNA construct", "HMIR0001"],
      competitorEquivalents: ["System Biosciences miRNA Precursor", "Thermo miRIDIAN Mimic"],
      internalOwner: "RNA Biology PM"
    },
    {
      id: "GC-LUC-PAIR",
      company: "GeneCopoeia",
      productName: "Luc-Pair Duo-Luciferase Assay Kit",
      catalogNumber: "LF001",
      rrid: "RRID:AB_3099004",
      productType: "Reporter assay kit",
      applicationArea: "Reporter assays",
      synonyms: ["Luc-Pair assay", "Duo-Luciferase Kit", "LF001 luciferase kit"],
      competitorEquivalents: ["Promega Dual-Luciferase Reporter Assay", "Thermo Pierce Luciferase"],
      internalOwner: "Assay Kits PM"
    },
    {
      id: "GC-EXOFECT",
      company: "GeneCopoeia",
      productName: "ExoFect Exosome Transfection Kit",
      catalogNumber: "EXFT10A-1",
      rrid: "RRID:AB_3099005",
      productType: "Transfection reagent",
      applicationArea: "Extracellular vesicle biology",
      synonyms: ["ExoFect kit", "exosome transfection kit", "EXFT10A"],
      competitorEquivalents: ["System Biosciences Exo-Fect", "Lonza Nucleofector"],
      internalOwner: "Delivery Products PM"
    }
  ],
  evidence: [
    {
      id: "SYN-PUB-001",
      sourceType: "publication",
      sourceTitle: "Synthetic publication example: pooled CRISPR screen workflow",
      sourceUrl: "https://example.org/synthetic/pub-001",
      sourceId: "SYN-PMID-001",
      date: "2026-01-12",
      authors: ["A. Rivera", "M. Chen", "S. Patel"],
      institution: "North Valley University",
      lab: "Rivera Functional Genomics Lab",
      country: "United States",
      snippet: "Methods used the GeneCopoeia SureVector CRISPR KO Kit HCP256001-LVSG03 for lentiviral knockout library validation in oncology cell models.",
      diseaseAreas: ["Oncology"],
      impactScore: 8.4,
      reviewStatus: "curated",
      confidenceScore: 0.86
    },
    {
      id: "SYN-PROT-002",
      sourceType: "protocol",
      sourceTitle: "Synthetic protocol example: reporter assay optimization",
      sourceUrl: "https://example.org/synthetic/protocol-002",
      sourceId: "SYN-PROT-002",
      date: "2026-02-18",
      authors: ["J. Wilson"],
      institution: "East Harbor Medical Center",
      lab: "Wilson Signal Transduction Core",
      country: "United States",
      snippet: "The Luc-Pair assay LF001 was used according to the protocol for promoter activity readouts after cytokine stimulation.",
      diseaseAreas: ["Inflammation"],
      reviewStatus: "curated",
      confidenceScore: 0.78
    },
    {
      id: "SYN-GRANT-003",
      sourceType: "grant",
      sourceTitle: "Synthetic grant example: extracellular vesicle RNA delivery",
      sourceUrl: "https://example.org/synthetic/grant-003",
      sourceId: "SYN-GRANT-003",
      date: "2026-03-04",
      authors: ["K. Morgan", "R. Singh"],
      institution: "Lakeside Research Institute",
      lab: "Morgan EV Biology Group",
      country: "United States",
      snippet: "The proposal names the ExoFect kit EXFT10A-1 as a planned reagent for exosome cargo loading studies in neuroinflammation.",
      diseaseAreas: ["Neuroscience", "Inflammation"],
      reviewStatus: "candidate",
      confidenceScore: 0.62
    },
    {
      id: "SYN-PAT-004",
      sourceType: "patent",
      sourceTitle: "Synthetic patent mention: ORF rescue construct panel",
      sourceUrl: "https://example.org/synthetic/patent-004",
      sourceId: "SYN-PAT-004",
      date: "2026-03-21",
      authors: ["D. Alvarez"],
      institution: "HelixBridge Therapeutics",
      lab: "Discovery Biology",
      country: "United States",
      snippet: "Example 3 references an OmicsLink ORF expression construct EX-HU12345-M02 as a rescue control in engineered cell lines.",
      diseaseAreas: ["Rare disease"],
      reviewStatus: "candidate",
      confidenceScore: 0.67
    },
    {
      id: "SYN-CONF-005",
      sourceType: "conference_abstract",
      sourceTitle: "Synthetic abstract: miRNA perturbation in fibrosis models",
      sourceUrl: "https://example.org/synthetic/conf-005",
      sourceId: "SYN-CONF-005",
      date: "2026-04-06",
      authors: ["L. Bennett", "N. Okafor"],
      institution: "North Valley University",
      lab: "Bennett RNA Lab",
      country: "United States",
      snippet: "Poster methods mention the GeneCopoeia miExpress miRNA clone HMIR0001-MR04 for precursor miRNA overexpression in fibrosis assays.",
      diseaseAreas: ["Fibrosis"],
      reviewStatus: "curated",
      confidenceScore: 0.8
    },
    {
      id: "SYN-TRIAL-006",
      sourceType: "trial",
      sourceTitle: "Synthetic clinical trial methods note: exosome assay development",
      sourceUrl: "https://example.org/synthetic/trial-006",
      sourceId: "SYN-NCT-006",
      date: "2026-04-22",
      authors: ["R. Singh"],
      institution: "Lakeside Research Institute",
      lab: "Translational Biomarkers Unit",
      country: "United States",
      snippet: "Sample processing plan uses EXFT10A-1 exosome transfection kit for assay feasibility work before clinical sample testing.",
      diseaseAreas: ["Oncology"],
      reviewStatus: "candidate",
      confidenceScore: 0.58
    },
    {
      id: "SYN-SOC-007",
      sourceType: "social_mention",
      sourceTitle: "Synthetic social mention: CRISPR reagent reorder intent",
      sourceUrl: "https://example.org/synthetic/social-007",
      sourceId: "SYN-SOC-007",
      date: "2026-04-30",
      authors: ["North Valley Core"],
      institution: "North Valley University",
      lab: "Genome Engineering Core",
      country: "United States",
      snippet: "Core facility post notes strong demand for GeneCopoeia CRISPR KO workflows and compares turnaround with Synthego CRISPR Kit.",
      diseaseAreas: ["Oncology"],
      reviewStatus: "candidate",
      confidenceScore: 0.52
    },
    {
      id: "SYN-PUB-008",
      sourceType: "publication",
      sourceTitle: "Synthetic publication example: dual luciferase comparison",
      sourceUrl: "https://example.org/synthetic/pub-008",
      sourceId: "SYN-PMID-008",
      date: "2026-05-03",
      authors: ["J. Wilson", "P. Osei"],
      institution: "East Harbor Medical Center",
      lab: "Wilson Signal Transduction Core",
      country: "United States",
      snippet: "The team benchmarked Luc-Pair Duo-Luciferase Assay Kit LF001 versus Promega Dual-Luciferase Reporter Assay for pathway screening.",
      diseaseAreas: ["Inflammation"],
      impactScore: 7.3,
      reviewStatus: "curated",
      confidenceScore: 0.83
    },
    {
      id: "SYN-GRANT-009",
      sourceType: "grant",
      sourceTitle: "Synthetic grant example: ORF clone array scale-up",
      sourceUrl: "https://example.org/synthetic/grant-009",
      sourceId: "SYN-GRANT-009",
      date: "2026-05-09",
      authors: ["D. Alvarez", "M. Chen"],
      institution: "HelixBridge Therapeutics",
      lab: "Discovery Biology",
      country: "United States",
      snippet: "Budget justification includes OmicsLink ORF Clone reagents and mentions a GenScript ORF Clone alternative for overflow demand.",
      diseaseAreas: ["Rare disease"],
      reviewStatus: "candidate",
      confidenceScore: 0.6
    },
    {
      id: "SYN-CONF-010",
      sourceType: "conference_abstract",
      sourceTitle: "Synthetic abstract: exosome delivery comparison",
      sourceUrl: "https://example.org/synthetic/conf-010",
      sourceId: "SYN-CONF-010",
      date: "2026-05-12",
      authors: ["K. Morgan"],
      institution: "Lakeside Research Institute",
      lab: "Morgan EV Biology Group",
      country: "United States",
      snippet: "The abstract compared ExoFect kit with System Biosciences Exo-Fect for exosome RNA cargo delivery.",
      diseaseAreas: ["Neuroscience"],
      reviewStatus: "curated",
      confidenceScore: 0.79
    },
    {
      id: "SYN-PUB-011",
      sourceType: "publication",
      sourceTitle: "Synthetic publication example: miRNA overexpression screen",
      sourceUrl: "https://example.org/synthetic/pub-011",
      sourceId: "SYN-PMID-011",
      date: "2026-05-16",
      authors: ["N. Okafor", "L. Bennett"],
      institution: "North Valley University",
      lab: "Bennett RNA Lab",
      country: "United States",
      snippet: "Materials and methods used RRID:AB_3099003 precursor miRNA constructs for pathway perturbation.",
      diseaseAreas: ["Fibrosis", "Oncology"],
      impactScore: 8.1,
      reviewStatus: "curated",
      confidenceScore: 0.84
    },
    {
      id: "SYN-SOC-012",
      sourceType: "social_mention",
      sourceTitle: "Synthetic social mention: reporter kit troubleshooting",
      sourceUrl: "https://example.org/synthetic/social-012",
      sourceId: "SYN-SOC-012",
      date: "2026-05-19",
      authors: ["Pathway Methods Forum"],
      institution: "East Harbor Medical Center",
      lab: "Wilson Signal Transduction Core",
      country: "United States",
      snippet: "Thread mentions no signal in an LF001 luciferase kit run until lysis timing was corrected.",
      diseaseAreas: ["Inflammation"],
      reviewStatus: "candidate",
      confidenceScore: 0.46
    }
  ],
  salesRecords: [
    {
      id: "SYN-SALE-001",
      productId: "GC-CRISPR-KO",
      accountName: "North Valley University",
      institution: "North Valley University",
      country: "United States",
      date: "2025-11-05",
      units: 3,
      revenue: 5400,
      orderType: "initial",
      sourceId: "ERP-SYN-001"
    },
    {
      id: "SYN-SALE-002",
      productId: "GC-CRISPR-KO",
      accountName: "North Valley University",
      institution: "North Valley University",
      country: "United States",
      date: "2026-04-25",
      units: 4,
      revenue: 7200,
      orderType: "reorder",
      sourceId: "ERP-SYN-002"
    },
    {
      id: "SYN-SALE-003",
      productId: "GC-LUC-PAIR",
      accountName: "East Harbor Medical Center",
      institution: "East Harbor Medical Center",
      country: "United States",
      date: "2026-01-30",
      units: 5,
      revenue: 3150,
      orderType: "initial",
      sourceId: "ERP-SYN-003"
    },
    {
      id: "SYN-SALE-004",
      productId: "GC-LUC-PAIR",
      accountName: "East Harbor Medical Center",
      institution: "East Harbor Medical Center",
      country: "United States",
      date: "2026-05-10",
      units: 6,
      revenue: 3780,
      orderType: "reorder",
      sourceId: "ERP-SYN-004"
    },
    {
      id: "SYN-SALE-005",
      productId: "GC-EXOFECT",
      accountName: "Lakeside Research Institute",
      institution: "Lakeside Research Institute",
      country: "United States",
      date: "2026-02-12",
      units: 2,
      revenue: 2400,
      orderType: "initial",
      sourceId: "ERP-SYN-005"
    },
    {
      id: "SYN-SALE-006",
      productId: "GC-ORF-CLONE",
      accountName: "HelixBridge Therapeutics",
      institution: "HelixBridge Therapeutics",
      country: "United States",
      date: "2026-03-28",
      units: 8,
      revenue: 9600,
      orderType: "initial",
      sourceId: "ERP-SYN-006"
    },
    {
      id: "SYN-SALE-007",
      productId: "GC-MIRNA-CLONE",
      accountName: "North Valley University",
      institution: "North Valley University",
      country: "United States",
      date: "2026-05-18",
      units: 3,
      revenue: 2850,
      orderType: "initial",
      sourceId: "ERP-SYN-007"
    }
  ]
};
